spring:
  application:
    name: discovery

server:
  port: 8761

eureka:
  server:
    renewalThresholdUpdateIntervalMs: 10000
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
