spring:
  application:
    name: demo

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 10
      leaseExpirationDurationInSeconds: 30

logging:
  level:
    org.springframework: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
